site_name: My Docs
nav:
  - Home: index.md
  - DNS:
      - 'General': 'dns/general.md'
      - 'Querying DNS data': 'dns/dig.md'
      - 'Installing and configuring Bind': 'dns/bind.md'
      - 'Reverse lookup': 'dns/reverse.md'
      - 'Forwarders': 'dns/forwarders.md'
      - 'Mail Exchange': 'dns/mail-exchange.md'
      - 'Further Excercises': 'dns/further-exercises.md'
  - LDAP:
      - 'General': 'ldap/general.md'
      - 'Browsing LDAP': 'ldap/browsing.md'
      - 'Installing and configuring OpenLDAP': 'ldap/set-up.md'
  - Acronyms: acronyms.md
