site_name: My Docs
nav:
  - Home: index.md
  - DNS:
      - 'General': 'dns/general.md'
      - 'Querying DNS data': 'dns/dig.md'
      - 'Installing and configuring Bind': 'dns/bind.md'
      - 'Reverse lookup': 'dns/reverse.md'
      - 'Forwarders': 'dns/forwarders.md'
      - 'Mail Exchange': 'dns/mail-exchange.md'
      - 'Transfer DNS configurations': 'dns/transfer-dns-configurations.md'
  - LDAP:
      - 'General': 'ldap/general.md'
      - 'Browsing LDAP': 'ldap/browsing.md'
      - 'Installing and configuring OpenLDAP': 'ldap/set-up.md'
      - 'Populating your DIT': 'ldap/populating.md'
      - 'Testing a bind operation as non-admin user': 'ldap/testing-bind-operation.md'
      - 'Extending an existing entry': 'ldap/extending-an-existing-entry.md'
      - 'Filter based search': 'ldap/filter-based-search.md'
      - 'Accessing LDAP data by using a mail client': 'ldap/mail-client.md'
      - 'LDAP Config': 'ldap/config.md'
  - Acronyms: acronyms.md
